### ISSUE TITLE
How Implement Middleware In laravel 11

### ISSUE THREAD

**Issue by milad-jfr** [PrevailExcel/laraquizbot#1]
How implement Middleware lines in Laravel 11 ,
on BotManController.php :

```
use App\Http\Middleware\PreventDoubleClicks;
$botman->middleware->captured(new PreventDoubleClicks);
```

Lines above not working because Laravel 11 does not have Middleware Folder like older versions

**Comment by PrevailExcel** [comment]
Laravel implements Middlewares a bi differently from the older versions.

To add midddlewares in Laravel 11, you have to add it inside the bootstrap/app.php file.


    ->withMiddleware(function (Middleware $middleware) {
        $middleware->validateCsrfTokens(except: [
            'botman',
        ]);

       //add your custom middlewares here.
    })
